#ifndef FXTR1_CORE_SIGNALTYPE_MQH
#define FXTR1_CORE_SIGNALTYPE_MQH

enum ENUM_FXTR1_SIGNAL_TYPE
{
   FXTR1_SIGNAL_NONE = 0,
   FXTR1_SIGNAL_ENTRY,
   FXTR1_SIGNAL_EXIT,
   FXTR1_SIGNAL_MANAGE
};

#endif
